FROM maven:3.8.7-eclipse-temurin-19-alpine

WORKDIR /app

COPY . .

ARG DATABASE_HOST
ARG DATABASE_PORT
ARG DATABASE_NAME
ARG DATABASE_USER
ARG DATABASE_PASSWORD

ENV DATABASE_HOST=$DATABASE_HOST
ENV DATABASE_PORT=$DATABASE_PORT
ENV DATABASE_NAME=$DATABASE_NAME
ENV DATABASE_USER=$DATABASE_USER
ENV DATABASE_PASSWORD=$DATABASE_PASSWORD

RUN echo "DATABASE_HOST=$DATABASE_HOST" > .env
RUN echo "DATABASE_PORT=$DATABASE_PORT" > .env
RUN echo "DATABASE_NAME=$DATABASE_NAME" > .env
RUN echo "DATABASE_USER=$DATABASE_USER" > .env
RUN echo "DATABASE_PASSWORD=$DATABASE_PASSWORD" > .env

RUN mvn clean package -Dspring.profiles.active=prod -DskipTests

EXPOSE 8080

CMD ["java", "-jar", "target/planner-0.0.1-SNAPSHOT.jar", "--spring.profiles.active=prod"]
